# baseURL = "https://example.com/"
languageCode = "en-us"
title = "AlahmadiQ8"
theme = "momo"
[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    codeFences = true
    guessSyntax = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[params]
  author = "Mohammad Alahmadi"
  description = "A tech blog about programming and software development"
  bio = """
  Hi. I'm a data and ai tech nerd from Kuwait. Outside of tech, I love board games, video games, weightlifting.

  In the age of overly AI-generated content, I try to keep this site as authentic as possible. 

  You can find my old posts at my [graveyard site](https://alahmadiq8.github.io/archive/).
  """ 
  profileImage = "/images/photo.jpg"
  [params.social]
    github = "https://github.com/alahmadiq8"
    linkedin = "https://www.linkedin.com/in/mohammad91/"
    # twitter = "https://twitter.com/yourusername"
    # email = "your@email.com"
